### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by kylekeppler** [bbaggerman/irig106lib#3]
Does the DLL have a version number anywhere?

Preferably this is accessible via an API call (so that I can check at runtime from user code) and in the repo source somewhere (so I can check at compile time).

**Comment by bbaggerman** [comment]
No but it has  been on my short list for a while. All that complicated major/minor/build number stuff seems outdated. I am inclined to use a version number that is nothing more than something derived from GIT. It looks like the foolproof way to do this is to use the git hash. It also looks like there is a git-describe command that may result in something more readable. I sure would like to compile something in rather than rely on something a human put in. Might have use tags, though.

**Comment by kylekeppler** [comment]
I'd recommend using tags. That way you can indicate to the user that a commit represents a releasable state and not something that may be broken.  

Git describe is neat. It will give you the last tag in the tree, indicate how many commits you are from it and the sha for the current commit.

You can even integrate that into the build process such that the version gets included in the compiled dll.

**Comment by kylekeppler** [comment]
Here is the microsofty way to do it: https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-versioning

**Comment by kylekeppler** [comment]
Thanks for fixing the c++ files. I'm bad at c++.
